apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: driftguard-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: app.driftguard.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: driftguard-web
            port:
              number: 80
  - host: api.driftguard.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: driftguard-api
            port:
              number: 80
