import React from 'react';
import { Activity, Beaker, ShieldAlert, AlertCircle } from 'lucide-react';

const MOCK_GRAPH_NODES = [
  { id: 'prompt_1', label: 'Prompt', type: 'prompt', local_score: 0.1, root_prob: 0.05, is_symptom: false },
  { id: 'retriever_1', label: 'Retriever (Stale Index)', type: 'retriever', local_score: 0.85, root_prob: 0.92, is_symptom: true },
  { id: 'reranker_1', label: 'Reranker', type: 'reranker', local_score: 0.2, root_prob: 0.15, is_symptom: false },
  { id: 'generator_1', label: 'Generator (Hallucination)', type: 'generator', local_score: 0.75, root_prob: 0.12, is_symptom: true },
  { id: 'policy_1', label: 'Policy Check', type: 'policy', local_score: 0.6, root_prob: 0.08, is_symptom: true }
];

export default function DiffusionViewerPage() {
  return (
    <div className="min-h-screen bg-gray-50 text-gray-900 p-8">
      <div className="max-w-5xl mx-auto">
        <div className="flex items-center justify-between mb-6">
          <h1 className="text-3xl font-bold tracking-tight text-gray-900 flex items-center gap-3">
            <Activity className="w-8 h-8 text-indigo-600" />
            Cross-Layer Drift Diffusion
          </h1>
          <div className="text-sm font-medium bg-white px-4 py-2 rounded-lg border shadow-sm flex items-center gap-2 text-gray-700">
            <Beaker className="w-4 h-4 text-indigo-500" />
            Model: Learned GAT (v1.0.0)
          </div>
        </div>
        
        <div className="bg-amber-50 border-l-4 border-amber-500 p-4 rounded-r-lg mb-8 shadow-sm">
          <div className="flex items-start gap-3">
            <ShieldAlert className="w-6 h-6 text-amber-600 mt-0.5 flex-shrink-0" />
            <div>
              <h3 className="text-sm font-bold text-amber-800">Scientific Restraint Disclaimer</h3>
              <p className="text-sm text-amber-700 mt-1">
                The attributions shown below are generated by <strong>learned graph diffusion</strong>. 
                This indicates statistical correlation based on historical fault data, but 
                <strong> does not imply causal proof</strong> until a ReplayEpisode confirms the diagnosis.
              </p>
            </div>
          </div>
        </div>
        
        <div className="bg-white rounded-xl shadow-sm border overflow-hidden">
          <div className="px-6 py-4 border-b bg-gray-50 flex justify-between items-center">
            <h2 className="text-lg font-semibold text-gray-800">Causal Graph Viewer</h2>
            <div className="flex gap-4 text-sm">
              <span className="flex items-center gap-1.5 text-gray-600">
                <div className="w-3 h-3 rounded-full bg-red-100 border border-red-300"></div> Local Symptom
              </span>
              <span className="flex items-center gap-1.5 text-gray-600">
                <div className="w-3 h-3 rounded-full bg-indigo-600 shadow-[0_0_8px_rgba(79,70,229,0.5)]"></div> Inferred Root Cause
              </span>
            </div>
          </div>
          
          <div className="p-8">
            <div className="flex flex-col gap-6">
              {MOCK_GRAPH_NODES.map((node, i) => (
                <div key={node.id} className="relative">
                  {/* Edges */}
                  {i < MOCK_GRAPH_NODES.length - 1 && (
                    <div className="absolute left-8 top-12 bottom-[-24px] w-0.5 bg-gray-200"></div>
                  )}
                  
                  <div className="flex items-center gap-6 relative z-10">
                    <div 
                      className={`w-16 h-16 rounded-full flex items-center justify-center font-bold text-lg border-2 transition-all duration-500
                        ${node.root_prob > 0.5 
                          ? 'bg-indigo-600 text-white border-indigo-700 shadow-[0_0_15px_rgba(79,70,229,0.5)] ring-4 ring-indigo-100' 
                          : node.is_symptom 
                            ? 'bg-red-50 text-red-700 border-red-200' 
                            : 'bg-white text-gray-400 border-gray-200'}`}
                    >
                      {(node.root_prob * 100).toFixed(0)}%
                    </div>
                    
                    <div className={`flex-1 p-4 rounded-lg border ${node.root_prob > 0.5 ? 'border-indigo-200 bg-indigo-50/30' : 'border-gray-100'}`}>
                      <div className="flex justify-between items-start">
                        <div>
                          <span className="text-xs font-mono font-medium text-gray-500 uppercase tracking-wider">{node.type}</span>
                          <h4 className="text-lg font-semibold text-gray-900">{node.label}</h4>
                        </div>
                        {node.root_prob > 0.5 && (
                          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-indigo-100 text-indigo-700 text-xs font-semibold">
                            <AlertCircle className="w-3 h-3" /> Likely Root Cause
                          </span>
                        )}
                      </div>
                      
                      <div className="mt-4 grid grid-cols-2 gap-4">
                        <div className="bg-white p-3 rounded border border-gray-100">
                          <div className="text-xs text-gray-500 mb-1">Local Detector Score</div>
                          <div className="font-mono text-sm">{(node.local_score * 100).toFixed(1)}%</div>
                        </div>
                        <div className="bg-white p-3 rounded border border-gray-100">
                          <div className="text-xs text-gray-500 mb-1">Diffused Root Prob</div>
                          <div className="font-mono text-sm text-indigo-700 font-semibold">{(node.root_prob * 100).toFixed(1)}%</div>
                        </div>
                      </div>
                      
                      {node.root_prob > 0.5 && (
                        <div className="mt-3 text-sm text-indigo-800 bg-indigo-100/50 p-2 rounded">
                          <strong>Explanation:</strong> High local score + propagated symptoms to Generator and Policy nodes.
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
