import React from 'react';

interface CertificateData {
  id: string;
  run_id: string;
  replay_episode_id: string;
  certificate_hash: string;
  issued_by: string;
  payload_summary: string;
  is_valid: boolean;
  evidence_kind: string;
}

interface RecoveryCertificateProps {
  certificate: CertificateData | null;
}

export function RecoveryCertificate({ certificate }: RecoveryCertificateProps) {
  if (!certificate) return null;

  return (
    <div className="w-full border border-[var(--foreground)] bg-[var(--background)] p-6 font-mono text-sm">
      <div className="flex justify-between items-start border-b border-[var(--foreground)] pb-4 mb-4">
        <div>
          <h2 className="text-xl font-bold uppercase tracking-widest mb-1">Recovery Certificate</h2>
          <p className="text-[var(--muted)] text-xs uppercase tracking-wider">Automated Fault Containment & Repair</p>
        </div>
        <div className="text-right">
          <div className={`px-2 py-1 text-xs font-bold inline-block border ${certificate.is_valid ? 'border-[var(--foreground)] text-[var(--foreground)] bg-transparent' : 'border-[var(--accent)] text-[var(--accent)] bg-transparent'}`}>
            {certificate.is_valid ? 'VALIDATED' : 'INVALID'}
          </div>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-x-8 gap-y-4 mb-6">
        <div>
          <span className="block text-[10px] text-[var(--muted)] uppercase mb-1">Certificate ID</span>
          <span className="block truncate">{certificate.id}</span>
        </div>
        <div>
          <span className="block text-[10px] text-[var(--muted)] uppercase mb-1">Target Run</span>
          <span className="block truncate">{certificate.run_id}</span>
        </div>
        <div>
          <span className="block text-[10px] text-[var(--muted)] uppercase mb-1">Issuer</span>
          <span className="block">{certificate.issued_by}</span>
        </div>
        <div>
          <span className="block text-[10px] text-[var(--muted)] uppercase mb-1">Evidence Kind</span>
          <span className="block">{certificate.evidence_kind}</span>
        </div>
        <div className="col-span-2">
          <span className="block text-[10px] text-[var(--muted)] uppercase mb-1">Cryptographic Hash</span>
          <span className="block truncate bg-[var(--foreground)] text-[var(--background)] p-2 text-xs">
            {certificate.certificate_hash}
          </span>
        </div>
      </div>

      <div className="border-t border-[var(--foreground)] pt-4">
        <span className="block text-[10px] text-[var(--muted)] uppercase mb-2">Diagnosis & Rationale</span>
        <p className="text-[var(--foreground)] text-sm leading-relaxed border-l-2 border-[var(--accent)] pl-4">
          {certificate.payload_summary}
        </p>
      </div>

      {/* Blueprint embellishments */}
      <div className="mt-8 pt-4 border-t border-[var(--muted)] border-dashed flex justify-between items-center text-[10px] text-[var(--muted)]">
        <span>Generated by DriftGuard-X BCRB</span>
        <span className="flex items-center gap-2">
          <span>SEC: CLASSIFIED</span>
          <span className="w-2 h-2 rounded-full bg-[var(--foreground)]"></span>
        </span>
      </div>
    </div>
  );
}
