"""Prompt 4: Auth and Tenant Models

Revision ID: 9ee98e79b741
Revises:
Create Date: 2026-08-22 10:35:37.418440

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ee98e79b741"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "detector_thresholds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.Column("detector_name", sa.String(length=128), nullable=False),
        sa.Column("feature_name", sa.String(length=128), nullable=False),
        sa.Column("threshold_value", sa.Float(), nullable=False),
        sa.Column("operator", sa.String(length=16), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_detector_thresholds_tenant_id", "detector_thresholds", ["tenant_id"], unique=False
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index("ix_tenants_slug", "tenants", ["slug"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("auth_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auth_subject"),
    )
    op.create_table(
        "agent_pipelines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("component_version_ids", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_agent_pipelines_tenant_id", "agent_pipelines", ["tenant_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=128), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_events_action", "audit_events", ["action"], unique=False)
    op.create_index("ix_audit_events_tenant_id", "audit_events", ["tenant_id"], unique=False)
    op.create_table(
        "component_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("component_type", sa.String(length=64), nullable=False),
        sa.Column("version_tag", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("component_type", "version_tag", name="uq_component_versions_type_tag"),
    )
    op.create_index(
        "ix_component_versions_type", "component_versions", ["component_type"], unique=False
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("request_path", sa.String(length=255), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "key", name="uq_idempotency_tenant_key"),
    )
    op.create_table(
        "tenant_memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("roles_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "tenant_id", name="uq_tenant_membership"),
    )
    op.create_index(
        "ix_tenant_memberships_tenant_id", "tenant_memberships", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_tenant_memberships_user_id", "tenant_memberships", ["user_id"], unique=False
    )
    op.create_table(
        "request_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=True),
        sa.Column("request_id", sa.String(length=255), nullable=True),
        sa.Column("commit_sha", sa.String(length=64), nullable=True),
        sa.Column("config_hash", sa.String(length=64), nullable=True),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column("hardware_id", sa.String(length=128), nullable=True),
        sa.Column("response_hash", sa.String(length=64), nullable=True),
        sa.Column("reliability_score", sa.Float(), nullable=True),
        sa.Column("reliability_vector", sa.JSON(), nullable=False),
        sa.Column("total_latency_ms", sa.Float(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("total_cost_usd", sa.Float(), nullable=True),
        sa.Column("error_type", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["agent_pipelines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_request_runs_created_at", "request_runs", ["created_at"], unique=False)
    op.create_index("ix_request_runs_pipeline_id", "request_runs", ["pipeline_id"], unique=False)
    op.create_index("ix_request_runs_status", "request_runs", ["status"], unique=False)
    op.create_index("ix_request_runs_tenant_id", "request_runs", ["tenant_id"], unique=False)
    op.create_table(
        "interventions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("intervention_type", sa.String(length=64), nullable=False),
        sa.Column("target_component_type", sa.String(length=64), nullable=False),
        sa.Column("from_version_id", sa.Uuid(), nullable=False),
        sa.Column("to_version_id", sa.Uuid(), nullable=False),
        sa.Column("from_version_tag", sa.String(length=64), nullable=False),
        sa.Column("to_version_tag", sa.String(length=64), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requires_human_approval", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["request_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_interventions_run_id", "interventions", ["run_id"], unique=False)
    op.create_table(
        "replay_state_manifests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("model_provider", sa.String(length=64), nullable=True),
        sa.Column("model_identifier", sa.String(length=128), nullable=True),
        sa.Column("model_config_hash", sa.String(length=64), nullable=True),
        sa.Column("prompt_template_hash", sa.String(length=64), nullable=True),
        sa.Column("retriever_version", sa.String(length=64), nullable=True),
        sa.Column("embedding_model_version", sa.String(length=64), nullable=True),
        sa.Column("vector_index_snapshot_id", sa.String(length=128), nullable=True),
        sa.Column("tool_schemas_hash", sa.String(length=64), nullable=True),
        sa.Column("policy_config_hash", sa.String(length=64), nullable=True),
        sa.Column("memory_snapshot_id", sa.String(length=128), nullable=True),
        sa.Column("random_seed", sa.Integer(), nullable=True),
        sa.Column("generation_parameters", sa.JSON(), nullable=False),
        sa.Column("container_image_digest", sa.String(length=128), nullable=True),
        sa.Column("dependency_lockfile_hash", sa.String(length=64), nullable=True),
        sa.Column("trace_root_hash", sa.String(length=64), nullable=True),
        sa.Column("manifest_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["request_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_replay_state_manifests_hash", "replay_state_manifests", ["manifest_hash"], unique=False
    )
    op.create_index(
        "ix_replay_state_manifests_run_id", "replay_state_manifests", ["run_id"], unique=False
    )
    op.create_table(
        "span_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("span_id", sa.String(length=16), nullable=False),
        sa.Column("parent_span_id", sa.String(length=16), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status_code", sa.String(length=16), nullable=False),
        sa.Column("status_message", sa.Text(), nullable=False),
        sa.Column("attributes_json", sa.JSON(), nullable=False),
        sa.Column("component_type", sa.String(length=64), nullable=True),
        sa.Column("component_version_id", sa.Uuid(), nullable=True),
        sa.Column("component_version_tag", sa.String(length=64), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=True),
        sa.Column("output_hash", sa.String(length=64), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("token_count_input", sa.Integer(), nullable=True),
        sa.Column("token_count_output", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("policy_result", sa.String(length=32), nullable=True),
        sa.Column("policy_rule_id", sa.String(length=128), nullable=True),
        sa.Column("error_type", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("redaction_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["request_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("span_id"),
    )
    op.create_index(
        "ix_span_records_component_type", "span_records", ["component_type"], unique=False
    )
    op.create_index("ix_span_records_run_id", "span_records", ["run_id"], unique=False)
    op.create_index("ix_span_records_tenant_id", "span_records", ["tenant_id"], unique=False)
    op.create_index("ix_span_records_trace_id", "span_records", ["trace_id"], unique=False)
    op.create_table(
        "symptom_registry",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("graph_node_id", sa.String(length=255), nullable=False),
        sa.Column("symptom_name", sa.String(length=255), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("detector_version", sa.String(length=64), nullable=False),
        sa.Column("evidence_snippet", sa.Text(), nullable=False),
        sa.Column("uncertainty", sa.Float(), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["request_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_symptom_registry_run_id", "symptom_registry", ["run_id"], unique=False)
    op.create_index(
        "ix_symptom_registry_tenant_id", "symptom_registry", ["tenant_id"], unique=False
    )
    op.create_table(
        "trace_artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.Column("spans_json", sa.JSON(), nullable=False),
        sa.Column("root_span_id", sa.String(length=16), nullable=True),
        sa.Column("total_span_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["request_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_index("ix_trace_artifacts_run_id", "trace_artifacts", ["run_id"], unique=False)
    op.create_index("ix_trace_artifacts_tenant_id", "trace_artifacts", ["tenant_id"], unique=False)
    op.create_table(
        "replay_episodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("original_run_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.Column("intervention_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("manifest_id", sa.Uuid(), nullable=True),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("swapped_component_type", sa.String(length=64), nullable=False),
        sa.Column("original_version_id", sa.Uuid(), nullable=False),
        sa.Column("replay_version_id", sa.Uuid(), nullable=False),
        sa.Column("original_version_tag", sa.String(length=64), nullable=False),
        sa.Column("replay_version_tag", sa.String(length=64), nullable=False),
        sa.Column("pinned_version_ids", sa.JSON(), nullable=False),
        sa.Column("original_reliability_vector", sa.JSON(), nullable=False),
        sa.Column("replay_reliability_vector", sa.JSON(), nullable=False),
        sa.Column("reliability_delta", sa.JSON(), nullable=False),
        sa.Column("original_reliability_score", sa.Float(), nullable=True),
        sa.Column("replay_reliability_score", sa.Float(), nullable=True),
        sa.Column("reliability_improvement", sa.Float(), nullable=True),
        sa.Column("original_request_hash", sa.String(length=64), nullable=True),
        sa.Column("replay_response_hash", sa.String(length=64), nullable=True),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column("commit_sha", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["intervention_id"],
            ["interventions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["manifest_id"],
            ["replay_state_manifests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["original_run_id"],
            ["request_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_replay_episodes_original_run_id", "replay_episodes", ["original_run_id"], unique=False
    )
    op.create_index("ix_replay_episodes_status", "replay_episodes", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_replay_episodes_status", table_name="replay_episodes")
    op.drop_index("ix_replay_episodes_original_run_id", table_name="replay_episodes")
    op.drop_table("replay_episodes")
    op.drop_index("ix_trace_artifacts_tenant_id", table_name="trace_artifacts")
    op.drop_index("ix_trace_artifacts_run_id", table_name="trace_artifacts")
    op.drop_table("trace_artifacts")
    op.drop_index("ix_symptom_registry_tenant_id", table_name="symptom_registry")
    op.drop_index("ix_symptom_registry_run_id", table_name="symptom_registry")
    op.drop_table("symptom_registry")
    op.drop_index("ix_span_records_trace_id", table_name="span_records")
    op.drop_index("ix_span_records_tenant_id", table_name="span_records")
    op.drop_index("ix_span_records_run_id", table_name="span_records")
    op.drop_index("ix_span_records_component_type", table_name="span_records")
    op.drop_table("span_records")
    op.drop_index("ix_replay_state_manifests_run_id", table_name="replay_state_manifests")
    op.drop_index("ix_replay_state_manifests_hash", table_name="replay_state_manifests")
    op.drop_table("replay_state_manifests")
    op.drop_index("ix_interventions_run_id", table_name="interventions")
    op.drop_table("interventions")
    op.drop_index("ix_request_runs_tenant_id", table_name="request_runs")
    op.drop_index("ix_request_runs_status", table_name="request_runs")
    op.drop_index("ix_request_runs_pipeline_id", table_name="request_runs")
    op.drop_index("ix_request_runs_created_at", table_name="request_runs")
    op.drop_table("request_runs")
    op.drop_index("ix_tenant_memberships_user_id", table_name="tenant_memberships")
    op.drop_index("ix_tenant_memberships_tenant_id", table_name="tenant_memberships")
    op.drop_table("tenant_memberships")
    op.drop_table("idempotency_keys")
    op.drop_index("ix_component_versions_type", table_name="component_versions")
    op.drop_table("component_versions")
    op.drop_index("ix_audit_events_tenant_id", table_name="audit_events")
    op.drop_index("ix_audit_events_action", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_agent_pipelines_tenant_id", table_name="agent_pipelines")
    op.drop_table("agent_pipelines")
    op.drop_table("users")
    op.drop_index("ix_tenants_slug", table_name="tenants")
    op.drop_table("tenants")
    op.drop_index("ix_detector_thresholds_tenant_id", table_name="detector_thresholds")
    op.drop_table("detector_thresholds")
    # ### end Alembic commands ###
