"""Add ingestion models and pgvector

Revision ID: 407792c02e8c
Revises: 579b59822548
Create Date: 2026-08-22 14:29:05.270571

"""
from __future__ import annotations

# revision identifiers, used by Alembic.
revision: str = '407792c02e8c'
down_revision: str | None = '579b59822548'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
