"""Prompt 5: Durable State Models

Revision ID: 78241866899b
Revises: 9ee98e79b741
Create Date: 2026-08-22 10:39:31.807150

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '78241866899b'
down_revision: str | None = '9ee98e79b741'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('requester_id', sa.String(length=255), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('risk_tier', sa.String(length=32), nullable=False),
    sa.Column('required_approvers', sa.Integer(), nullable=False),
    sa.Column('two_person_control', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delegated_approvers', sa.JSON(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_requests_status', 'approval_requests', ['status'], unique=False)
    op.create_index('ix_approval_requests_tenant_id', 'approval_requests', ['tenant_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_tenant_id', 'jobs', ['tenant_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('commit_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('merkle_root', sa.String(length=64), nullable=False),
    sa.Column('certificate_count', sa.Integer(), nullable=False),
    sa.Column('policy_snapshot', sa.Text(), nullable=False),
    sa.Column('canary_passed', sa.Boolean(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commit_hash')
    )
    op.create_index('ix_ledger_entries_commit_hash', 'ledger_entries', ['commit_hash'], unique=False)
    op.create_index('ix_ledger_entries_tenant_id', 'ledger_entries', ['tenant_id'], unique=False)
    op.create_table('recovery_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.String(length=255), nullable=False),
    sa.Column('current_status', sa.String(length=32), nullable=False),
    sa.Column('capsule_id', sa.String(length=255), nullable=True),
    sa.Column('timeout_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('event_log_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id')
    )
    op.create_index('ix_recovery_states_status', 'recovery_states', ['current_status'], unique=False)
    op.create_index('ix_recovery_states_tenant_id', 'recovery_states', ['tenant_id'], unique=False)
    op.create_table('approval_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_break_glass', sa.Boolean(), nullable=False),
    sa.Column('break_glass_justification', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Enable Row-Level Security for PostgreSQL
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # List of tenant-scoped tables
        tables = [
            "jobs", "approval_requests", "recovery_states", "ledger_entries"
        ]

        for table in tables:
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
            op.execute(f"""
                CREATE POLICY tenant_isolation_policy ON {table}
                USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', TRUE), '')::uuid);
            """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Policies must be removed while their tables still exist.  The legacy
    # downgrade attempted this after dropping the tables, which made a full
    # PostgreSQL rollback impossible.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        tables = [
            "jobs", "approval_requests", "recovery_states", "ledger_entries"
        ]
        for table in tables:
            op.execute(f"DROP POLICY IF EXISTS tenant_isolation_policy ON {table};")
            op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")

    op.drop_table('approval_decisions')
    op.drop_index('ix_recovery_states_tenant_id', table_name='recovery_states')
    op.drop_index('ix_recovery_states_status', table_name='recovery_states')
    op.drop_table('recovery_states')
    op.drop_index('ix_ledger_entries_tenant_id', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_commit_hash', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('ix_jobs_tenant_id', table_name='jobs')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_approval_requests_tenant_id', table_name='approval_requests')
    op.drop_index('ix_approval_requests_status', table_name='approval_requests')
    op.drop_table('approval_requests')

    # ### end Alembic commands ###
