"""prompt_7_recovery_eligibility_certificate

Revision ID: 579b59822548
Revises: 78241866899b
Create Date: 2026-08-22 10:59:50.129360

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '579b59822548'
down_revision: str | None = '78241866899b'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_certificates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('original_trace_root_hash', sa.String(length=64), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('intervention_hash', sa.String(length=64), nullable=False),
    sa.Column('measured_resource_budget_and_usage', sa.JSON(), nullable=False),
    sa.Column('replay_outcome', sa.String(length=32), nullable=False),
    sa.Column('reliability_delta', sa.Float(), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('policy_decision', sa.String(length=32), nullable=False),
    sa.Column('approval_decision_set', sa.JSON(), nullable=False),
    sa.Column('canary_result_hash', sa.String(length=64), nullable=False),
    sa.Column('recovery_capsule_hash', sa.String(length=64), nullable=False),
    sa.Column('executor_image_digest', sa.String(length=128), nullable=False),
    sa.Column('signer_identity', sa.String(length=128), nullable=False),
    sa.Column('signature_b64', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recovery_certificates_capsule', 'recovery_certificates', ['recovery_capsule_hash'], unique=False)
    op.create_index('ix_recovery_certificates_tenant_id', 'recovery_certificates', ['tenant_id'], unique=False)
    op.create_index('ix_recovery_certificates_trace', 'recovery_certificates', ['original_trace_root_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recovery_certificates_trace', table_name='recovery_certificates')
    op.drop_index('ix_recovery_certificates_tenant_id', table_name='recovery_certificates')
    op.drop_index('ix_recovery_certificates_capsule', table_name='recovery_certificates')
    op.drop_table('recovery_certificates')
    # ### end Alembic commands ###
